In [145]:
import os
import numpy as np
import xlrd

%run helperfx.py

In [146]:
def ConvertMedToModelData(filename, CasVar, MaltoVar):
    
    # Extracts lick data form medfiles
    data = medfilereader(filename, varsToExtract=[CasVar, MaltoVar], remove_var_header=True)
    LicksL = data[0]
    LicksR = data[1]

    # Combines left and right licks
    LicksAll = np.asarray(LicksL+LicksR)
    LicksAll_code = np.asarray([1]*len(LicksL) + [2]*len(LicksR))

    # orders licks in time and sorts coded lick train
    inds = np.argsort(LicksAll)

    LicksAll_sorted = LicksAll[inds]
    LicksAll_code_sorted = LicksAll_code[inds]

    # uses ILIs to find gaps between clusters
    LicksAll_diff = np.diff(LicksAll_sorted)
    gaps = [i for i, x in enumerate(LicksAll_diff) if x > 0.5]

    # Adds zeros to produce gaps between clusters
    gaps.reverse()
    for idx in gaps:
        LicksAll_code_sorted = np.insert(LicksAll_code_sorted, idx+1, 0)

    # Inserts a zero at the start of lick train to match model data
    LicksAll_code_sorted = np.insert(LicksAll_code_sorted, 0, 0)

    return LicksAll_code_sorted

In [152]:
xlfile = 'R:\\DA_and_Reward\\gc214\\IPP3\\IPP3_expdetails.xlsx'
metafilename = 'IPP3_metafile'

metafilemaker(xlfile, metafilename, fileformat='txt')

metadata, header = metafilereader(metafilename+'.txt')

In [172]:
medfolder = 'R:\\DA_and_Reward\\gc214\\IPP3\\MED-PC datafile\\'

test1_data_NR = {}
test1_data_PR = {}

for row in metadata:
    if row[2] == 's4':
        rat = row[1]
        filename = medfolder + row[0]
        
        if 'cas' in row[6]:
            casvar = 'b'
            maltvar = 'e'
        if 'cas' in row[7]:
            casvar = 'e'
            maltvar = 'b'        
        
        output = ConvertMedToModelData(filename, casvar, maltvar)
        
        if row[4] == 'NR': 
            test1_data_NR[rat] = output
        if row[4] == 'PR': 
            test1_data_PR[rat] = output

In [173]:
# for i in test1_data_PR:
#     print(test1_data_PR[i])
#     print(len([x for x in test1_data_PR[i] if x == 1]))

[0 1 1 ... 1 1 1]
4775
[0 2 2 ... 2 2 2]
4638
[0 2 2 ... 1 1 1]
1854
[0 1 1 ... 1 0 1]
1466
[0 1 0 ... 1 1 1]
513
[0 1 1 ... 0 1 1]
3015


In [1]:
print('Extracted licks from Med data')

Extracted licks from Med data
